### ISSUE TITLE
The script waits for too long on profiles with 0 posts on Instagram.

### ISSUE THREAD

**Issue by mustjbr** [akurtovic/InstaRaider#14]
Examples:
Cai0 has 0 posts on Instagram.
Loading Instagram profile...
Saving photos to ./Images/Cai0/
------
Photos saved so far:
---------10--------20--------30--------40--------50
#
------
Saved 1 new images to ./Images/Cai0/
Cai_0 has 0 posts on Instagram.
Loading Instagram profile...
Saving photos to ./Images/Cai_0/
------
Photos saved so far:
---------10--------20--------30--------40--------50

**Comment by akurtovic** [comment]
I don't think this is a big deal unless you're using this to cycle through many Instagram profiles to mine photos (a use case InstaRaider wasn't made for), but I did just push a commit that checks the image count and fails fast for profiles with 0 post. It doesn't make sense to load the profile if you already know there are no photos there. Thanks for reporting the issue.
