### ISSUE TITLE
Support for videos download. (Done)

### ISSUE THREAD

**Issue by Lowbreeze** [akurtovic/InstaRaider#24]
Hello, akurtovic I understand this is not a issue, however I wanted to run something by you and wasn't really sure of the best way to reach you. However, iv been using your InstaRaider program for some time now and really like it, and wanted to commit some work to it, spec the support for videos downloads, Iv made a branch of the repo on my profile, and got it to work, however it may need work but never the less I wanted you to look over it, I'm not big on GitHub, I'm not sure how to run commits and stuff, my current repo isn't up to date with yours and I'm having a hard time understanding how to use GitHub properly and syncing your repo, Iv worked on the code for some time, but iv been putting it off alot lately due to not knowing what I'm doing here :( ... I feel this commit would be a big part of your work and I don't want my work to go unnoticed, and I would like nothing more to be a contributor to your project. I'm just lacking the knowledge of GitHub. PS when you have time could you take a look at my branch?

**Comment by akurtovic** [comment]
Sorry I'm just responding now. I've put this project on the back burner for a while. I tried to look at your fork but I didn't see any of your commits there. I could have missed it in my cursory glance. You can always just email me at amirkurtovic@gmail.com if you want and I can help you figure out the Git stuff.
