### ISSUE TITLE
Only downloading 25 images.

### ISSUE THREAD

**Issue by dannyvoid** [akurtovic/InstaRaider#39]
Every time I try to download a full profile (1300 images) with metadata, it stops at 25 images.

**Comment by provolot** [comment]
I had this problem, too. It's because the JSON data that Instagram includes in the source only contains 25 images. Fixed in PR #41.

**Comment by akurtovic** [comment]
Confirmed that PR #41 fixes this issue. Thanks for the commit @provolot and thanks for reporting this issue @dannyvoid
