### ISSUE TITLE
Not actually working : style statement

### ISSUE THREAD

**Issue by soubhiksb** [akurtovic/InstaRaider#4]
Whenever I'm running this code I'm getting the error:
>Traceback (most recent call last):
> File "instaRaider.py", line 235, in <module>
>    raider.getPhotos(source, userName, count)
>  File "instaRaider.py", line 163, in getPhotos
>    rawUrl = x['style']
>  File "build/bdist.macosx-10.10-intel/egg/bs4/element.py", line 905, in __getitem__
>KeyError: 'style'

**Comment by akurtovic** [comment]
That's because it looks like Instagram recently changed their front-end to use React. The entire structure of the HTML is different and all of the CSS selectors are now broken. Should be easy to fix but might take me a few weeks before I can get to it.

**Comment by akurtovic** [comment]
The latest commit should have fixed this issue. Please let me know if it works for you.
