### ISSUE TITLE
Instagram's Term of Use

### ISSUE THREAD

**Issue by od320** [akurtovic/InstaRaider#43]
Hi,

I want to be sure usage of this really great code doesn't go against any of instagram's term of use. However, the following highlighted portion in the image below suggests it does? Guys, what do you think? 
![image](https://cloud.githubusercontent.com/assets/11770378/12080547/7c0e8822-b25e-11e5-828d-291a7921eaf7.png)

**Comment by akurtovic** [comment]
@od320 I did review Instagram's Terms of Use and Privacy Policy before creating this repo and that's one of the reasons the Disclaimer starts with: "This code is posted for informational purposes only." While I'm not a lawyer (and you should never take legal advice from non-lawyers) I think it's safe to say that if you're using this tool to scrape a bunch of images from different profiles you are clearly in violation of Instagram's Terms of Use. I only use it when testing new pull requests, and only on my own profile. This tool was originally developed as a way to let you backup your Instagram photos, inspired by my frustration of switching from an Android to an iPhone and being unable to use one of my old Instagram photos as a profile pic on another service. So I guess the gist of what I'm saying is, use it responsibly. I hope that answers your question.

**Comment by od320** [comment]
Hi Amir,

 

 

Thanks for the detailed response. I get the gist, makes perfect sense!
