### ISSUE TITLE
Feature Request: Captions

### ISSUE THREAD

**Issue by michaelcummings** [akurtovic/InstaRaider#44]
First of all, awesome script. Works perfect. Kudos for finding an elegant solution

I may be able to add this functionality myself at some point, but I was just curious if you have any plans to also capture the caption. I'd like to be able to make full backups of my accounts including captions. Comments are not so important, but having a CSV file that has the filename and full caption would be helpful...

Cheers

**Comment by akurtovic** [comment]
@michaelcummings A feature like this was already added by #34 but it's not documented yet. Hope that works for you.
