### ISSUE TITLE
downloading private profiles which I have access to

### ISSUE THREAD

**Issue by ahmedahmedov** [akurtovic/InstaRaider#46]
Cannot download a private profile to which I have an access.

**Comment by freeman212** [comment]
I agree this is an issue. Would be cool if there was an option to pass your login credentials in order to view (and download) private profiles you're subscribed to.

**Comment by dannyvoid** [comment]
I created a simple work around, that has yet to cause any bugs for me.

- Make sure you have Firefox installed.
- Make sure you have signed into Instagram on Firefox.
- Then you need to edit the code for InstaRaider.

Change 

```
    def setup_webdriver(self):
        self.profile = webdriver.FirefoxProfile()
```

Into

```
    def setup_webdriver(self):
        self.profile = webdriver.FirefoxProfile("location/of/your/firefox/profile")
```

You should only do this if you know what you're doing.

**Comment by ahmedahmedov** [comment]
cool. I will try your workaround. thanks

**Comment by freeman212** [comment]
thanks, @dannyvoid.
Unfortunately though I'm using firefox headless so I can't sign in first using the browser. Hope there will be an easier method provided by the tool itself.

**Comment by akarambir** [comment]
@freeman212 I had to use this feature and due to this script detecting some css selector, it was not able to continue after login. I have added way to pass your login creds for private profiles. Check it out here https://github.com/akarambir/InstaRaider

PS: I needed to run this for multiple usernames instead of giving a username in command line. So you might need to have a look at it.

**Comment by freeman212** [comment]
@akarambir sounds cool.
I've tried to revert the part with the json file to pass one username at the time so it doesn't break the functionality of my wrapper script. unfortunately I'm receiving this error though (must've messed something up somehow, the arguments should be okay)...
> usage: instaRaider.py [-h] [-n NUM_TO_DOWNLOAD] [-l LOG_LEVEL] [-m] [-v]
                      [-p PROCESS_NUMBER]
                      username directory
instaRaider.py: error: unrecognized arguments: -u -w

Can you tell me how to format the json file with usernames in an array so I can test your script?

**Comment by akarambir** [comment]
@freeman212 json file should be something like:

```json
[
"abc",
"def",
"mike",
"foo",
bar"
]
```

In the arguments, give the path to this file. Also your output is not showing my additional command line options. You are still using the original `InstaRaider` and not my fork

**Comment by dannyvoid** [comment]
@akarambir This is non-related, but I have no other way to ask.
I really like your fork of this, but I've run into an issue I am not able to fix.
I can set the directory to download images, and they will all goto directory/username

But, I need the images to go into directory/username/anotherSubFolder

Obviously I can't do this with just the directory command, I can only change the directory leading up to the username, nothing after. So, I need to change something in your fork. 

What would be the easiest way to achieve this?

**Comment by freeman212** [comment]
@akarambir where was my head yesterday :see_no_evil: my wrapper script was still pointing to the old working directory.
it's working like a charm now, thank you very much !

**Comment by akarambir** [comment]
@dannyvoid This is the line where we are doing that https://github.com/akarambir/InstaRaider/blob/master/instaRaider.py#L479

You can change this line to:

```python
directory = op.join(base_directory, username, 'anotherSubFolder')
```

**Comment by dannyvoid** [comment]
Thanks! Solved that issue, but I've come across something else.
I have a json file with quite a few usernames, but it only processes the first 13, then the script closes like it did it's job. No errors.

**Comment by akarambir** [comment]
@dannyvoid It shouldn't happen. The primary reason I had to go route of having json file with usernames is I had more than 50 usernames that I had to download photos of(for research). And it is working for me. Does it end abruptly(missing some log messages) or with all the logs that it normally show?

Another thing that may be happening is the 14th username is invalid. The original script was exiting after that and I haven't changed it.

**Comment by dannyvoid** [comment]
@akarambir Late response: All of the normal logs, and I double checked all of the usernames. They are all valid. If somehow I could somehow send you my json file (privately), and you could possibly debug this issue (when you have the free time, of course) that would be great.

**Comment by akarambir** [comment]
@dannyvoid I can help you with that. You can share your json with me via mail: my github username at google mail service.

**Comment by smithy285** [comment]
@akarambir Getting:

`Traceback` (most recent call last):
  File "instaRaider.py", line 497, in <module>
    main()
  File "instaRaider.py", line 480, in main
    os.makedirs(directory, exist_ok=True)
TypeError: makedirs() got an unexpected keyword argument 'exist_ok'
``

**Comment by smithy285** [comment]
@akarambir Fixed it by changing your code to use this fix: https://github.com/Diaoul/subliminal/commit/43d02c349f4c1f26c27b66897356c024e0ff18df

**Comment by distantstar** [comment]
I don't understand why you're creating cache_dir and not keeping it at directory?

**Comment by distantstar** [comment]
@smithy285 I don't understand why you're creating cache_dir and not keeping it at directory?
