### ISSUE TITLE
TypeError: super()

### ISSUE THREAD

**Issue by lucasrca** [akurtovic/InstaRaider#52]
Traceback (most recent call last):
  File "./instaRaider.py", line 484, in <module>
    main()
  File "./instaRaider.py", line 479, in main
    raider.download_photos()
  File "./instaRaider.py", line 254, in download_photos
    downloader = MultiDownloader(photo_url, self.headers, photo_name)
  File "./instaRaider.py", line 53, in **init**
    super().**init**()
TypeError: super() takes at least 1 argument (0 given)
## 

OS: Debian Jessie 8.3 amd64
Python 2.7.9
## pip 1.5.6 from /usr/lib/python2.7/dist-packages (python 2.7)

Made some changes:

OBS: I am not a python programmer, but I've added the following code:

<-- super().**init**()
--> super(self.**class**,self).**init**()

And it worked.

**Comment by Nidnogg** [comment]
Got the same issue, can't quite seem to fix it. I'm not sure where to add the code.

**Comment by lucasrca** [comment]
Line 53

On Mon, Mar 28, 2016 at 6:50 PM, Nidnogg <notifications@github.com> wrote:

> Got the same issue, can't quite seem to fix it. I'm not sure where to add
> the code.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/akurtovic/InstaRaider/issues/52#issuecomment-202594799>
>


PGP: A590 0A62 88AC 07FA CA95  36CB 068B 8A1D 8C84 2153
<http://drakentecnologia.com/wp-content/uploads/2015/05/lucas.asc>
"*Talk is cheap. Show me the code" - Linus Torvalds*

**Comment by Nidnogg** [comment]
Oh, that's where I was replacing it. I got something different though, my init looks like this by default `super().__init__()`
instead of
`super().init()`
like in your comment. Am I missing something? Sorry if this comes off as terribly newbish but I'm not really familiar with Python.

**Comment by lucasrca** [comment]
You are right. The code is: super().__init__()
Just change to what I've wrote on the issue tracker.

On Mon, Mar 28, 2016 at 7:08 PM, Nidnogg <notifications@github.com> wrote:

> Oh, that's where I was replacing it. I got something different though, my
> init looks like this by default super().__init__()
> instead of
> super().init()
> like in your comment. Am I missing something? Sorry if this comes off as
> terribly newbish but I'm not really familiar with Python.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/akurtovic/InstaRaider/issues/52#issuecomment-202599596>
>



-- 
Atenciosamente,

*Lucas Almeida*
*System Administrator*
PGP: A590 0A62 88AC 07FA CA95  36CB 068B 8A1D 8C84 2153
<http://drakentecnologia.com/wp-content/uploads/2015/05/lucas.asc>
"*Talk is cheap. Show me the code" - Linus Torvalds*

**Comment by akurtovic** [comment]
I think this is an issue introduced by https://github.com/akurtovic/InstaRaider/pull/49, and occurs only if you are not running Python 3. I'll test a fix for Python 2.7.x as soon as I get a chance unless somebody wants to open a merge request.

**Comment by lucasrca** [comment]
Thanks.

On Tue, Mar 29, 2016 at 1:31 PM, Amir Kurtovic <notifications@github.com>
wrote:

> I think this is an issue introduced by #49
> <https://github.com/akurtovic/InstaRaider/pull/49>, and occurs only if
> you are not running Python 3. I'll test a fix for Python 2.7.x as soon as I
> get a chance unless somebody wants to open a merge request.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/akurtovic/InstaRaider/issues/52#issuecomment-202986492>
>



-- 
Atenciosamente,

*Lucas Almeida*
*System Administrator*
PGP: A590 0A62 88AC 07FA CA95  36CB 068B 8A1D 8C84 2153
<http://drakentecnologia.com/wp-content/uploads/2015/05/lucas.asc>
"*Talk is cheap. Show me the code" - Linus Torvalds*
