### ISSUE TITLE
Multidownloader class not working.

### ISSUE THREAD

**Issue by makudesu** [akurtovic/InstaRaider#56]
Traceback (most recent call last):
  File "instaRaider.py", line 484, in <module>
    main()
  File "instaRaider.py", line 479, in main
    raider.download_photos()
  File "instaRaider.py", line 254, in download_photos
    downloader = MultiDownloader(photo_url, self.headers, photo_name)
  File "instaRaider.py", line 53, in __init__
    super().__init__()

TypeError: super() takes at least 1 argument (0 given)
This version 63505fb2fdbb459a7e468fa00360aafd8aa71a6f is working though.

**Comment by dannyvoid** [comment]
I only encountered this issue with python 2. Upgrading to 3 resolved it for me.

**Comment by makudesu** [comment]
I think this issue is caused by python 3.

**Comment by makudesu** [comment]
I've applied the fix. https://github.com/akurtovic/InstaRaider/pull/57

**Comment by makudesu** [comment]
It works on python 2.7.6 now, should I try this fix on python 3 too?

**Comment by makudesu** [comment]
It works on python 3!

**Comment by makudesu** [comment]
I've created a pull request  here #58.
