### ISSUE TITLE
Unable to get videos

### ISSUE THREAD

**Issue by nihild3v** [akurtovic/InstaRaider#62]
It doesn't detect videos
ex:
> python instaRaider.py -v emyvonhell ./emyvonhell
...
...
Skipping file emyvonhell/11191424_826419970740837_189256057_n.jpg as it already exists.
Saved 0 files to emyvonhell
Saving videos to emyvonhell
Saved 0 videos to emyvonhell

What do I do wrong? thanks.

**Comment by harrydet** [comment]
Did you find any solution for this?
