### ISSUE TITLE
The party is over

### ISSUE THREAD

**Issue by nihild3v** [akurtovic/InstaRaider#63]
ig-dl creepyyeha creepyyeha/
User creepyyeha has no photos to download.

Not detect any photo... :(

**Comment by jhnsmth** [comment]
It happens because instagram has slightly changed the style of JSON in the response. I'm gonna send a PR tomorrow. But you can fix it by yourself, just change a line 122 to:
>         counts_code = re.search(r'\"media": {"count": \d+', response.text)

Good parties never end  ;)

**Comment by NitroXenon** [comment]
Is it better to ignore the spaces between ```media``` and ```{``` using regex?

**Comment by nihild3v** [comment]
Ready! Thanks a lot. My line was 97
Starting the party again... :-)

**Comment by jhnsmth** [comment]
@NitroXenon  thanks. It's a nice idea.  I'll add to  the PR.
