### ISSUE TITLE
says " instaRaider.py: error: the following arguments are required: username, directory"

### ISSUE THREAD

**Issue by nikunjbaheti** [akurtovic/InstaRaider#75]
I have tried multiple times solving this error, still to no avail
this is the output `C:\Users\nikun\Desktop\Python\InstaRaider>instaRaider.py -n 100 ttt_official C:\
usage: instaRaider.py [-h] [-n NUM_TO_DOWNLOAD] [-l LOG_LEVEL] [-m] [-v]
                      [-p PROCESS_NUMBER]
                      username directory
instaRaider.py: error: the following arguments are required: username, directory`

**Comment by distantstar** [comment]
Try quoting the path you want to store the directory. "C:\"

**Comment by nikunjbaheti** [comment]
tried that then I got the same error. Maybe its because I am using Windows 10?
